<#
.SYNOPSIS
    One-command onboarding (REPO-BASELINE §3).

.DESCRIPTION
    The PowerShell twin of scripts/setup.sh. Both exist because a setup
    instruction that only works on one platform fails at step one of onboarding
    for half the team (IDENTITY-AND-ACCOUNTS §10) — and `openssl` is not a
    command on Windows, so the secret below is generated by the runtime we
    already depend on rather than by an external tool.

.PARAMETER Check
    Report what is missing and change nothing.

.EXAMPLE
    ./scripts/setup.ps1
    ./scripts/setup.ps1 -Check
#>
[CmdletBinding()]
param([switch]$Check)

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $repoRoot

$appHost = 'src/ArchitectureStandardsInitExample.AppHost'
$script:missing = 0

function Write-Step { param([string]$Text) Write-Host ""; Write-Host $Text }
function Write-Ok   { param([string]$Text) Write-Host "  [ ok ] $Text" }
function Write-Skip { param([string]$Text) Write-Host "  [ -- ] $Text" }
function Write-Fail { param([string]$Text) Write-Host "  [FAIL] $Text"; $script:missing++ }
function Write-Note { param([string]$Text) Write-Host "  $Text" }

# --- 1. Prerequisites -------------------------------------------------------
Write-Step "1. Prerequisites"

$dotnet = Get-Command dotnet -ErrorAction SilentlyContinue
if ($dotnet) {
    $sdk = (& dotnet --version)
    if ($sdk -like '10.*') { Write-Ok ".NET SDK $sdk" }
    else {
        Write-Fail ".NET SDK $sdk found, but this solution targets net10.0."
        Write-Note "       Install 10.0: https://dotnet.microsoft.com/download/dotnet/10.0"
    }
} else {
    Write-Fail ".NET SDK 10 not found — https://dotnet.microsoft.com/download/dotnet/10.0"
}

$node = Get-Command node -ErrorAction SilentlyContinue
if ($node) {
    $nodeVersion = (& node --version)
    $nodeMajor = [int]($nodeVersion -replace '^v(\d+).*', '$1')
    if ($nodeMajor -ge 20) { Write-Ok "Node $nodeVersion" }
    else { Write-Fail "Node $nodeVersion found; Next.js needs 20 or newer — https://nodejs.org" }
} else {
    Write-Fail "Node 20+ not found — https://nodejs.org"
}

if (Get-Command pnpm -ErrorAction SilentlyContinue) { Write-Ok "pnpm $(& pnpm --version)" }
else { Write-Fail "pnpm not found — 'corepack enable pnpm', or https://pnpm.io/installation" }

# Optional prerequisites: named, so that skipping is informed (P8).
if (Get-Command docker -ErrorAction SilentlyContinue) {
    Write-Ok "docker $((& docker --version) -replace '^Docker version ([^,]+),.*', '$1')"
} else {
    Write-Skip "docker not found (optional — needed only to build the container images"
    Write-Note "       locally; 'dotnet run' uses the in-memory database)."
    Write-Note "       https://docs.docker.com/get-docker/"
}

if (Get-Command gitleaks -ErrorAction SilentlyContinue) { Write-Ok "gitleaks installed" }
else {
    Write-Skip "gitleaks not found (optional — needed for the pre-commit secret scan in"
    Write-Note "       step 4; the CI job runs regardless). 'winget install gitleaks'"
}

if ($Check) {
    Write-Step "Check complete."
    if ($script:missing -gt 0) {
        Write-Note "$($script:missing) required tool(s) missing — see the FAIL lines above."
        exit 1
    }
    Write-Note "Everything required is installed. Run ./scripts/setup.ps1 to finish setup."
    exit 0
}

if ($script:missing -gt 0) {
    Write-Step "Stopping: $($script:missing) required tool(s) missing."
    Write-Note "Install them and run this script again."
    exit 1
}

# --- 2. Dependencies --------------------------------------------------------
Write-Step "2. Restoring dependencies"
& dotnet restore ArchitectureStandardsInitExample.sln
if ($LASTEXITCODE -ne 0) { throw "dotnet restore failed." }
Write-Ok ".NET packages restored"

Push-Location web
try {
    & pnpm install --frozen-lockfile
    if ($LASTEXITCODE -ne 0) { throw "pnpm install failed." }
} finally { Pop-Location }
Write-Ok "frontend packages installed"

# --- 3. The one mandatory secret, generated ---------------------------------
# Generated, never invented (IDENTITY-AND-ACCOUNTS §10). Hex only — '+', '/',
# '=' and ';' all mean something inside a connection string.
Write-Step "3. Local secret store"
& dotnet user-secrets init --project $appHost | Out-Null

$existing = (& dotnet user-secrets list --project $appHost 2>$null) -join "`n"
if ($existing -match 'Parameters:postgres-password') {
    Write-Ok "postgres-password already present in user-secrets — left untouched"
} else {
    $bytes = [byte[]]::new(24)
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($bytes)
    $generated = [System.Convert]::ToHexString($bytes).ToLowerInvariant()
    & dotnet user-secrets set "Parameters:postgres-password" $generated --project $appHost | Out-Null
    Write-Ok "generated postgres-password into user-secrets (48 hex chars)"
}

Write-Note ""
Write-Note "  Where that value goes, once:"
Write-Note "    dotnet user-secrets  ->  AppHost AddParameter('postgres-password', secret: true)"
Write-Note "      ->  the postgres container's POSTGRES_PASSWORD"
Write-Note "      ->  ConnectionStrings__apidb, injected into the API by WithReference"
Write-Note "  In deployment the same key is a Fly secret instead. See flyio/SECRETS.md."

# --- 4. Optional: the pre-commit secret scan --------------------------------
Write-Step "4. Pre-commit secret scan  (optional — needed to catch a credential before it becomes history)"
if (Get-Command gitleaks -ErrorAction SilentlyContinue) {
    Copy-Item scripts/hooks/pre-commit .git/hooks/pre-commit -Force
    Write-Ok "hook installed at .git/hooks/pre-commit"
} else {
    Write-Skip "skipped: gitleaks is not installed."
    Write-Note "       Without it a credential can reach your local history. The CI job"
    Write-Note "       still blocks it from reaching the default branch."
}

# --- 5. Optional: telemetry export ------------------------------------------
Write-Step "5. Telemetry export  (optional — needed to send traces somewhere other than the Aspire dashboard)"
if ($env:OTEL_EXPORTER_OTLP_ENDPOINT) {
    Write-Ok "OTEL_EXPORTER_OTLP_ENDPOINT is set to $($env:OTEL_EXPORTER_OTLP_ENDPOINT)"
} else {
    Write-Skip "not set. Telemetry is still collected and shown in the Aspire dashboard;"
    Write-Note "       it is simply not exported anywhere else. No feature is lost."
}

# --- Done -------------------------------------------------------------------
Write-Step "Setup complete."
Write-Note ""
Write-Note "  Run the whole system:   dotnet run --project $appHost"
Write-Note "  Run the tests:          dotnet test"
Write-Note "  Scan for secrets:       ./scripts/scan-secrets.sh"
Write-Note ""
Write-Note "  If something fails, the troubleshooting table in scripts/README.md is keyed"
Write-Note "  on the exact error text — paste the message and search for it."
